import { Recursive } from 'next/font/google'
import './globals.css'

const recursive = Recursive({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-recursive'
  // You can specify variable axes like weight, casual, mono, etc.
  // For example, to include specific weights:
  // weight: ['300', '400', '700'],
  // Or to use the variable font features:
  // variable: '--font-recursive', // Define a CSS variable for use with Tailwind CSS
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${recursive.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  )
}

export default RootLayout
